name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'liberica'
          java-version: '21.0.1+12'
      - name: Maven Verify
        run: mvn -B clean verify
      - name: Test Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Checkstyle
        uses: dbelyaev/action-checkstyle@v1.9.0
        with:
          github_token: ${{ secrets.github_token }}
          workdir: ./
          checkstyle_config: checkstyle/checkstyle.xml
          filter_mode: diff_context
          fail_on_error: true
          reporter: github-pr-review
          level: error
